// ai-design-platform-web/packages/ai-workflow/src/App.tsx
import React from 'react';
import { Routes, Route, NavLink } from 'react-router-dom';
import { routes } from './router';
import { onGlobalStateChange } from '@ai-design/micro-core';

const App: React.FC = () => {
  React.useEffect(() => {
    onGlobalStateChange((state, prev) => {
      console.log('[ai-workflow] global state changed:', state, prev);
    });
  }, []);

  return (
    <div className="ai-workflow p-6">
      <h1 className="text-2xl font-bold text-gray-800 mb-4">AI 工作流</h1>
      <nav className="flex space-x-4 mb-6">
        <NavLink
          to="/"
          className={({ isActive }) =>
            `text-blue-600 hover:underline ${isActive ? 'font-bold' : ''}`
          }
        >
          首页
        </NavLink>
        <NavLink
          to="/about"
          className={({ isActive }) =>
            `text-blue-600 hover:underline ${isActive ? 'font-bold' : ''}`
          }
        >
          关于
        </NavLink>
      </nav>
      <Routes>
        {routes.map((route) => (
          <Route key={route.path} path={route.path} element={route.element} />
        ))}
      </Routes>
    </div>
  );
};

export default App;

// ai-design-platform-web/packages/ai-generation-app/src/App.vue
<template>
  <div class="ai-generation-app p-6">
    <h1 class="text-2xl font-bold text-gray-800 mb-4">AI 生成</h1>
    <nav class="flex space-x-4 mb-6">
      <router-link to="/" class="text-blue-600 hover:underline"> 首页 </router-link>
      <router-link to="/about" class="text-blue-600 hover:underline"> 关于 </router-link>
    </nav>
    <router-view />
  </div>
</template>

<script setup lang="ts">
import { onGlobalStateChange } from '@ai-design/micro-core';
onGlobalStateChange((state, prev) => {
  console.log('[ai-generation-app] global state changed:', state, prev);
});
</script>
